d /etc/qtr 0750 root qtr -
d /var/lib/qtr 0750 qtr qemu -
d /var/lib/qtr/state 0700 qtr qtr -
d /var/lib/qtr/images 2770 qtr qemu -
d /var/lib/qtr/images/.uploads 2770 qtr qemu -
d /var/lib/qtr/iso 2750 qtr qemu -
d /var/lib/qtr/iso/.uploads 2750 qtr qemu -
d /var/lib/qtr/logs 2770 qtr qemu -
