/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessRouteImport } from './routes/access'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInstallationsIndexRouteImport } from './routes/_authenticated/installations/index'
import { Route as AuthenticatedInstallationsIdRouteImport } from './routes/_authenticated/installations/$id'
import { Route as AuthenticatedResourcesImagesRouteImport } from './routes/_authenticated/resources/images'
import { Route as AuthenticatedResourcesMediaRouteImport } from './routes/_authenticated/resources/media'
import { Route as AuthenticatedVmsIndexRouteImport } from './routes/_authenticated/vms/index'
import { Route as AuthenticatedVmsNameRouteRouteImport } from './routes/_authenticated/vms/$name/route'
import { Route as AuthenticatedVmsNameIndexRouteImport } from './routes/_authenticated/vms/$name/index'
import { Route as AuthenticatedVmsNameConsoleRouteImport } from './routes/_authenticated/vms/$name/console'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstallationsIndexRoute =
  AuthenticatedInstallationsIndexRouteImport.update({
    id: '/installations/',
    path: '/installations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstallationsIdRoute =
  AuthenticatedInstallationsIdRouteImport.update({
    id: '/installations/$id',
    path: '/installations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesImagesRoute =
  AuthenticatedResourcesImagesRouteImport.update({
    id: '/resources/images',
    path: '/resources/images',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesMediaRoute =
  AuthenticatedResourcesMediaRouteImport.update({
    id: '/resources/media',
    path: '/resources/media',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVmsIndexRoute = AuthenticatedVmsIndexRouteImport.update({
  id: '/vms/',
  path: '/vms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVmsNameRouteRoute =
  AuthenticatedVmsNameRouteRouteImport.update({
    id: '/vms/$name',
    path: '/vms/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVmsNameIndexRoute =
  AuthenticatedVmsNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVmsNameRouteRoute,
  } as any)
const AuthenticatedVmsNameConsoleRoute =
  AuthenticatedVmsNameConsoleRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => AuthenticatedVmsNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/access': typeof AccessRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings': typeof AuthenticatedSettingsRoute
  '/vms/$name': typeof AuthenticatedVmsNameRouteRouteWithChildren
  '/installations/$id': typeof AuthenticatedInstallationsIdRoute
  '/resources/images': typeof AuthenticatedResourcesImagesRoute
  '/resources/media': typeof AuthenticatedResourcesMediaRoute
  '/installations/': typeof AuthenticatedInstallationsIndexRoute
  '/vms/': typeof AuthenticatedVmsIndexRoute
  '/vms/$name/console': typeof AuthenticatedVmsNameConsoleRoute
  '/vms/$name/': typeof AuthenticatedVmsNameIndexRoute
}
export interface FileRoutesByTo {
  '/access': typeof AccessRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/installations/$id': typeof AuthenticatedInstallationsIdRoute
  '/resources/images': typeof AuthenticatedResourcesImagesRoute
  '/resources/media': typeof AuthenticatedResourcesMediaRoute
  '/installations': typeof AuthenticatedInstallationsIndexRoute
  '/vms': typeof AuthenticatedVmsIndexRoute
  '/vms/$name/console': typeof AuthenticatedVmsNameConsoleRoute
  '/vms/$name': typeof AuthenticatedVmsNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access': typeof AccessRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vms/$name': typeof AuthenticatedVmsNameRouteRouteWithChildren
  '/_authenticated/installations/$id': typeof AuthenticatedInstallationsIdRoute
  '/_authenticated/resources/images': typeof AuthenticatedResourcesImagesRoute
  '/_authenticated/resources/media': typeof AuthenticatedResourcesMediaRoute
  '/_authenticated/installations/': typeof AuthenticatedInstallationsIndexRoute
  '/_authenticated/vms/': typeof AuthenticatedVmsIndexRoute
  '/_authenticated/vms/$name/console': typeof AuthenticatedVmsNameConsoleRoute
  '/_authenticated/vms/$name/': typeof AuthenticatedVmsNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings'
    | '/vms/$name'
    | '/installations/$id'
    | '/resources/images'
    | '/resources/media'
    | '/installations/'
    | '/vms/'
    | '/vms/$name/console'
    | '/vms/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings'
    | '/'
    | '/installations/$id'
    | '/resources/images'
    | '/resources/media'
    | '/installations'
    | '/vms'
    | '/vms/$name/console'
    | '/vms/$name'
  id:
    | '__root__'
    | '/_authenticated'
    | '/access'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/vms/$name'
    | '/_authenticated/installations/$id'
    | '/_authenticated/resources/images'
    | '/_authenticated/resources/media'
    | '/_authenticated/installations/'
    | '/_authenticated/vms/'
    | '/_authenticated/vms/$name/console'
    | '/_authenticated/vms/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessRoute: typeof AccessRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installations/': {
      id: '/_authenticated/installations/'
      path: '/installations'
      fullPath: '/installations/'
      preLoaderRoute: typeof AuthenticatedInstallationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installations/$id': {
      id: '/_authenticated/installations/$id'
      path: '/installations/$id'
      fullPath: '/installations/$id'
      preLoaderRoute: typeof AuthenticatedInstallationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources/images': {
      id: '/_authenticated/resources/images'
      path: '/resources/images'
      fullPath: '/resources/images'
      preLoaderRoute: typeof AuthenticatedResourcesImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources/media': {
      id: '/_authenticated/resources/media'
      path: '/resources/media'
      fullPath: '/resources/media'
      preLoaderRoute: typeof AuthenticatedResourcesMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vms/': {
      id: '/_authenticated/vms/'
      path: '/vms'
      fullPath: '/vms/'
      preLoaderRoute: typeof AuthenticatedVmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vms/$name': {
      id: '/_authenticated/vms/$name'
      path: '/vms/$name'
      fullPath: '/vms/$name'
      preLoaderRoute: typeof AuthenticatedVmsNameRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vms/$name/': {
      id: '/_authenticated/vms/$name/'
      path: '/'
      fullPath: '/vms/$name/'
      preLoaderRoute: typeof AuthenticatedVmsNameIndexRouteImport
      parentRoute: typeof AuthenticatedVmsNameRouteRoute
    }
    '/_authenticated/vms/$name/console': {
      id: '/_authenticated/vms/$name/console'
      path: '/console'
      fullPath: '/vms/$name/console'
      preLoaderRoute: typeof AuthenticatedVmsNameConsoleRouteImport
      parentRoute: typeof AuthenticatedVmsNameRouteRoute
    }
  }
}

interface AuthenticatedVmsNameRouteRouteChildren {
  AuthenticatedVmsNameConsoleRoute: typeof AuthenticatedVmsNameConsoleRoute
  AuthenticatedVmsNameIndexRoute: typeof AuthenticatedVmsNameIndexRoute
}

const AuthenticatedVmsNameRouteRouteChildren: AuthenticatedVmsNameRouteRouteChildren =
  {
    AuthenticatedVmsNameConsoleRoute: AuthenticatedVmsNameConsoleRoute,
    AuthenticatedVmsNameIndexRoute: AuthenticatedVmsNameIndexRoute,
  }

const AuthenticatedVmsNameRouteRouteWithChildren =
  AuthenticatedVmsNameRouteRoute._addFileChildren(
    AuthenticatedVmsNameRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVmsNameRouteRoute: typeof AuthenticatedVmsNameRouteRouteWithChildren
  AuthenticatedInstallationsIdRoute: typeof AuthenticatedInstallationsIdRoute
  AuthenticatedResourcesImagesRoute: typeof AuthenticatedResourcesImagesRoute
  AuthenticatedResourcesMediaRoute: typeof AuthenticatedResourcesMediaRoute
  AuthenticatedInstallationsIndexRoute: typeof AuthenticatedInstallationsIndexRoute
  AuthenticatedVmsIndexRoute: typeof AuthenticatedVmsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVmsNameRouteRoute: AuthenticatedVmsNameRouteRouteWithChildren,
  AuthenticatedInstallationsIdRoute: AuthenticatedInstallationsIdRoute,
  AuthenticatedResourcesImagesRoute: AuthenticatedResourcesImagesRoute,
  AuthenticatedResourcesMediaRoute: AuthenticatedResourcesMediaRoute,
  AuthenticatedInstallationsIndexRoute: AuthenticatedInstallationsIndexRoute,
  AuthenticatedVmsIndexRoute: AuthenticatedVmsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessRoute: AccessRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
